### ISSUE TITLE
failed when it start into Fedora Linux

### ISSUE THREAD

**Issue by kuboosoft** [ntadej/tano#57]
I compiled it into Fedora Linux 64bits, but doesn't start...

[makerpm@localhost ~]$ tano
tano: error while loading shared libraries: libtanocore.so.1.99: cannot open shared object file: Error 40

The symlink is installed /usr/lib/libtanocore.so.1.99 also I made a symlink to /usr/lib64/libtanocore.so.1.99 without results.

*** Now using...

cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_SKIP_RPATH=ON -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DWITH_QT5:BOOL=OFF -DLIB_SUFFIX=64 -DDEFAULT_DATA_DIR=/usr/share/tano -DDISABLE_UPDATE_CHECK=1

[makerpm@localhost ~]$ tano
Tano 1.99.2
Copyright (C) 2015 Tadej Novak

Violación de segmento (`core' generado)
[makerpm@localhost ~]$

**Comment by ntadej** [comment]
There were some updates and this is probably fixed.
