### ISSUE TITLE
Can't build with latest libvlc-qt from git

### ISSUE THREAD

**Issue by mrjavum** [ntadej/tano#59]
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Build Tano Player: ON
Enable logging: ON
Build statically: OFF
You are compiling Tano 1.99.2
Git Version Patch: f5d8852

CMake Error at cmake/FindLIBVLCQT.cmake:67 (MESSAGE):
  Could not find libvlc-qt
Call Stack (most recent call first):
  CMakeLists.txt:182 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/javum/aur/tano/src/tano/CMakeFiles/CMakeOutput.log".

**Comment by ntadej** [comment]
There is a `feature/vlc-qt` branch which should fix the issues.
