### ISSUE TITLE
Somoto.e potentially unwanted app install integrated without warning

### ISSUE THREAD

**Issue by sambul13** [ntadej/tano#63]
In current binaries ESET Smart Security finds Somoto.E potentially unwanted app (http://www.somotoinc.com/) that hijacks PC web browsers offering paid downloads. Here is screenshot (http://oi63.tinypic.com/vra8g0.jpg).

Also, Malwarebytes shows multiple warnings while Tano at install attempts to contact malicious website (http://oi67.tinypic.com/20pc00y.jpg) several times.

Why don't you clearly show Install options:
1. Also install extra paid per click or potentially unwanted apps

I wonder if offering force install of extra potentially unwanted apps without user warning or blocking options is in compliance with Github software posting policies.

**Comment by ntadej** [comment]
Thank you for letting me know. It seems that it depends on region, as I didn't have any problems when implementing it. I will remove it from the installer asap.
